export const ErrorCodes = {
    lexer: {
        UNEXPECTED_QUOTE: "LEX001",
        UNTERMINATED_STRING: "LEX002",
        ILLEGAL_CHARACTER: "LEX003",
        INVALID_ESCAPE: "LEX004",
    },
    parser: {
        UNEXPECTED_TOKEN: "PAR001",
        MISSING_EXPRESSION: "PAR002",
        EXPECTED_IDENTIFIER: "PAR003",
        SYNTAX_ERROR: "PAR004",
        UNEXPECTED_END_OF_INPUT: "PAR005",
        MISSING_GREATER_THAN: "PAR006",
        MISSING_LEFT_PAREN: "PAR007",
        MISSING_RIGHT_PAREN: "PAR008",
        MISSING_RETURN_TYPE: "PAR009",
        MISSING_ARROW: "PAR010",
        VARIADIC_PARAMETER_ERROR: "PAR011",
        MISSING_TYPE_ANNOTATION: "PAR012",
        MISSING_WHILE_KEYWORD: "PAR013",
        MISSING_LEFT_BRACE: "PAR014",
        MISSING_RIGHT_BRACE: "PAR015",
        MISSING_RETURN_KEYWORD: "PAR016",
        MISSING_SEMICOLON: "PAR017",
        MISSING_BREAK_KEYWORD: "PAR018",
        MISSING_CONTINUE_KEYWORD: "PAR019",
        MISSING_IF_KEYWORD: "PAR020",
        MISSING_LET_OR_CONST: "PAR021",
        INVALID_MUT_CONST_COMBO: "PAR022",
        EXPECTED_EQUAL_SIGN: "PAR023",
        EXPECTED_TYPE_KEYWORD: "PAR024",
        EXPECTED_CONSTRAINT_IDENTIFIER: "PAR025",
        EXPECTED_TYPE_PARAMETER_NAME: "PAR026",
        INVALID_ASSIGNMENT_TARGET: "PAR027",
        MISSING_COLON: "PAR028",
        MISSING_LEFT_BRACKET: "PAR029",
        MISSING_RIGHT_BRACKET: "PAR030",
        MISSING_DOT: "PAR031",
        EXPECTED_STRING: "PAR032",
        EXPECTED_BOOLEAN: "PAR033",
        EXPECTED_NUMBER: "PAR034",
        INVALID_CONSTANT: "PAR035",
        EXPECTED_STRUCT_KEYWORD: "PAR036",
        EXPECTED_STRUCT_NAME: "PAR037",
        EXPECTED_FIELD_NAME: "PAR038",
        EXPECTED_ENUM_KEYWORD: "PAR039",
        EXPECTED_ENUM_NAME: "PAR040",
        MISSING_COMMA: "PAR041",
        EXPECTED_VARIANT_NAME: "PAR042",
        EXPECTED_MODULE_NAME: "PAR043",
        EXPECTED_MODULE_KEYWORD: "PAR044",
        INVALID_EXPORT_NODE: "PAR045",
        EXPECTED_IMPORT_KEYWORD: "PAR046",
        EXPECTED_USE_KEYWORD: "PAR047",
        INVALID_MIX_SET_COMBO: "PAR048",
        MISSING_FOR_KEYWORD: "PAR049",
        MISSING_EQ_ARROW: "PAR050",
        INVALID_EXPRESSION_POSITION: "PAR051",
        MALFORMED_MAP_KEY: "PAR052",
        EXPECTED_MAP_KEYWORD: "PAR053",
        EXPECTED_SET_KEYWORD: "PAR054",
    },
    runtime: {
        UNDEFINED_SYMBOL: "RUN001",
        UNDEFINED_MODULE: "RUN002",
        INVALID_SUPER_REFERENCE: "RUN003",
        MISSING_STRUCT_FIELD: "RUN004",
        NOT_CALLABLE: "RUN005",
        UNDEFINED_FUNCTION: "RUN006",
        STACK_UNDERFLOW: "RUN007",
        UNDEFINED_PROPERTY: "RUN008",
        OPERATION_FAILED: "RUN009",
        UNSUPPORTED_OPERATOR: "RUN010",
        UNDEFINED_VARIABLE: "RUN011",
        MISSING_MAIN: "RUN012",
    },
    string_lexer: {

    },
    string_parser: {
        UNEXPECTED_END_OF_INPUT: "SPAR001",
        EXPECTED_TEXT: "SPAR002",
        EXPECTED_PLACEHOLDER: "SPAR003",

    },
    string_runtime: {

    },
};

// Helper function to get the category
export const getCategory = (errorCode: string) => {
    if (errorCode.startsWith('LEX')) return 'Lexer';
    if (errorCode.startsWith('PAR')) return 'Parser';
    if (errorCode.startsWith('RUN')) return 'Runtime';
    return 'Unknown';
};
